name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          api-level: 35
          build-tools: "35.0.0"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew clean assembleDebug --no-daemon --stacktrace

      - name: Unit tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

      - name: Lint
        run: ./gradlew lintDebug --no-daemon --stacktrace

      - name: Static analysis
        run: ./gradlew ktlintCheck detekt --no-daemon --stacktrace
